name: ci

on:
  push:
  pull_request:
  schedule:
    - cron: '16 6 * * *'
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "sharmasecureservicesusa/devbuilder"
          install: true
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: "${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMG_LEAF }}:latest"
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
  
